cloud:
  aws:
    region: us-west-2
    credentials:
      accessKey: <accessKey>
      secretKey: <secretKey>
    s3:
      bucketName: <bucket name>
    endpointUrl: end point URL         
multipart:
  maxFileSize: -1
  maxRequestSize: 1024Mb
  

  